### ISSUE TITLE
Version 1.1.2?

### ISSUE THREAD

**Issue by tueda** [MersenneTwister-Lab/TinyMT#11]
Because `CHANGE-LOG.txt` mention "ver. 1.1.2" while the README files say "ver. 1.1.1" and there is no tag "v1.1.2",  I was wondering if the version 1.1.2 is an ongoing project. Or should the current codebase be considered as version 1.1.2?

To avoid possible confusion, maybe `CHANGE-LOG.txt` needs release date information for each version.

(By the way, there is a typo in `README.md`, `s/TitinyMT/TinyMT/`.)

**Comment by MSaito** [comment]
Thank you.
I've added new tag v1.1.2
